### ISSUE TITLE
Transmitting SIGINT from Python to OCaml

### ISSUE THREAD

**Issue by jonathan-laurent** [janestreet/pythonlib#13]
I am using pythonlib to call an OCaml library in one of my Python projects. One thing I have particularly appreciated so far is how smooth the error handling is (e.g. OCaml exceptions are correctly transmitted to Python). However, I have noticed that when Python calls some non-terminating OCaml code, the application does not react to SIGINT (Ctrl+C) anymore.

Would there be a way to transmit the SIGINT signal to OCaml in these cases?
In particular, this would make debugging of non-terminating functions much smoother, enabling OCaml to catch a SIGINT and maybe print a backtrace.

**Comment by LaurentMazare** [comment]
It's certainly possible to set a signal handler on the ocaml side and so be able to perform arbitrary actions when a sigint is triggered (ctrl+c in a python interpreter, or the stop button in a jupyter notebook). Then the tricky bit is how to interrupt the computation and give the control back to the user: I don't think there is a generally good solution there, the OCaml toplevel has some hacks to raise an exception in this case but it's unclear to me how robust this bit is, and whether this is bytecode specific or would also apply to native code.
What we ended up doing when binding functions that use the Async library is to give these functions access to an `interrupted` deferred so that they can run the cleanup code that they would want, and potentially can check for interruptions at several points during the computation.

**Comment by jonathan-laurent** [comment]
This is interesting, thank you!
Do you have a pointer to an example using the `interrupted` deferred mechanism that you just mentioned?

**Comment by LaurentMazare** [comment]
Sadly this bit is not on our open-source version so as to avoid having a dependency to async in pythonlib. I'll check how difficult it is to craft a pythonlib-async open-source package but it might be quite some effort for what it would bring.

**Comment by jonathan-laurent** [comment]
I agree that writing a pythonlib-async may not have the best possible work to impact ratio.
Thanks for your insights!
