### ISSUE TITLE
Dealing with uncaught exceptions

### ISSUE THREAD

**Issue by jonathan-laurent** [janestreet/pythonlib#3]
Right now, it appears that when an OCaml function is called from python and raises an uncaught exception, the python interpreter terminates silently:
```
> ipython -i examples-gen/test.py
In [1]: odate.of_string('2020-03-03')                                                                                                                                                        
Out[1]: <capsule object "ocaml-capsule" at 0x7f3809401810>
In [2]: odate.of_string('-1')                                                                                                                                                                
Fatal error: executable program file not found
fish: “ipython -i examples-gen/test.py” terminated by signal SIGABRT (Abort)
```
Are you aware of a workaround to get at least an error message or a stack trace?

**Comment by LaurentMazare** [comment]
That seems to indeed be a pitfall of the automated generation, this part is not much used as far as I know and some bits are certainly lacking.
On the other hand, the manual way of writing bindings via `Py_module` and `Defunc` is pretty much battle tested. In this context, we rely on [wrap_ocaml_errors](https://github.com/janestreet/pythonlib/blob/v0.14/src/py_module.ml#L37-L49) to intercept ocaml exceptions and convert them to python exceptions. The wrapping is a bit verbose though, so in order to be a bit more python idiomatic, we recommend using `value_errorf` on the ocaml side at the bindings level, and these will directly translate into python exceptions without additional wrapping.

**Comment by theKidOfArcrania** [comment]
Having some issues with this too :(

Dug a little bit deeper, seems like it's related to [this issue](https://github.com/ocaml/ocaml/issues/9344). Turns out, building a shared object builds it with the `-output-complete-obj` flag, which means the ocaml runtime has no way of extracting debug symbols from the binary (since it built the entire runtime into the same binary). 

A way around it is to use the pass the .cds file using the `CAML_DEBUG_FILE` environment variable whenever we run python, which is generated when the .c file is generated. Unfortunately, the way dune build system is set up, the .cds file is written to your /tmp directory under some generated filename. I dunno whether if there's a way to tell where to put the .cds (haven't taken enough time to play around with the ocamlc/dune build system to do this).
